#!/bin/bash

usage_params() {
	echo "server package"
	echo "package: [package_group:]package_name"
}

. $(dirname $0)/aem_common

server=$(resolve_server $1)
resolve_package $2

url="$server/crx/packmgr/service/.json/etc/packages/$package_group/$package_name.zip?cmd=replicate"
call -X POST $url
