#!/bin/bash

usage_params() {
	echo "[-o output] server package"
	echo "output: file to output to, defaults to package_name, - for stdout"
	echo "server: protocol://hostname of server to send to, may be an alias from ~/.aemcli"
	echo "package: [package_group:]package_name"
}

. $(dirname $0)/aem_common

output=
if [ "$1" == "-o" ]; then
	output=$2
	[ "$output" != "-" ] || output=/dev/stdout
	shift 2
fi

server=$(resolve_server $1)
resolve_package $2

[ "$output" ] || output=$package_name.zip
call $server$package_jcr > $output
