#!/bin/bash

usage_params() {
	echo "[-i] server file"
	echo "output: file to output to, defaults to package_name, - for stdout"
	echo "server: protocol://hostname of server to send to, may be an alias from ~/.aemcli"
	echo "package: [package_group:]package_name"
}

. $(dirname $0)/aem_common

install=false
if [ "$1" == "-i" ]; then
	install=true
	shift
fi

server=$(resolve_server $1)
file=$2

url="$server/crx/packmgr/service/.json/?cmd=upload&force=true"
output=$(call -F "package=@$file;filename=file.zip" $url)
echo $output

package=$(echo $output | sed -ne 's|.*"path":"/etc/packages/\(.*\)/\(.*\)-\(.*\).zip"}|\1:\2:\3|p')
if [ $package ] && $install; then
	$(dirname $0)/aem_pkg_install $server $package
fi
