#!/bin/bash

usage_params() {
	echo "server"
	echo "server: protocol://hostname of server to send to, may be an alias from ~/.aemcli"
}

. $(dirname $0)/aem_common

if [ "$1" = "-a" ]; then
	filter() { cat; }
	shift
elif [ "$1" = "--previous" ]; then
	filter() { grep -v '[*]$'; }
	shift
else
	filter() { sed -ne 's/ [*]$//p'; }
fi

server=$(resolve_server $1)
url=$server/etc/packages.tidy.2.json

call $url | perl -ne '
	if (/^    "([^"]*?)(?:-([0-9\.]+))?\.zip": {/) {
		print "$group:$1:$2\n";
	}
	if (/^  "([^"]*)"/) {
		$group = $1;
	}
' | sort -t: -k1,2 -s | perl -ne '
	while(<STDIN>) {
		if (/^(.*:.*):(.*)$/) {
			$artefact = $1;
			$version = $2;
			if ($last_artefact) {
				print "$last_artefact:$last_version ";
				if ($last_artefact ne $artefact) {
					print "*";
				}
				print "\n";
			}
			$last_artefact = $artefact;
			$last_version = $version;
		}
	}
	if ($last_artefact) {
		print "$last_artefact:$last_version *\n";
	}
' | filter
